services:
    webpy:
      build: ./python
      ports: 
        - 1020:5000
      volumes:
        - ./python:/code
      environment:
        FLASK_DEBUG: "true"
    redis:
      image: "redis:alpine"
    webgo:
      build: ./go
      ports: 
        - 1030:8030

        